// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khaioggjxusobutcexxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoYWlvZ2dqeHVzb2J1dGNleHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzM2ODYsImV4cCI6MjA1NzUwOTY4Nn0.EfEscuOtowzHM5obReDKkajIuRTzTfrrLLhowSioOc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);